# Generated by Django 5.2.4 on 2025-07-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("image_name", models.CharField(max_length=255)),
                ("soil_type", models.CharField(max_length=50)),
                ("confidence", models.FloatField()),
            ],
        ),
    ]
